# Generated by Django 5.2.6 on 2025-11-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
