# Generated by Django 5.2.6 on 2025-11-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='day',
            field=models.CharField(blank=True, choices=[('monday', 'lunes'), ('tuesday', 'martes'), ('wednesday', 'miércoles'), ('thursday', 'jueves'), ('friday', 'viernes'), ('saturday', 'sábado'), ('sunday', 'domingo')], max_length=100, null=True),
        ),
    ]
